---
- name: Packages
  ansible.builtin.include_tasks: "packages-{{ ansible_pkg_mgr }}.yml"
- name: Install sysstat
  ansible.builtin.include_tasks: sysstat.yml
- name: Users
  ansible.builtin.include_tasks: users.yml
- name: Poor mans DNS
  ansible.builtin.include_tasks: poor_mans_dns.yml
  when: linux_poor_mans_dns
