---
- name: Packages
  ansible.builtin.include_tasks: "packages-{{ ansible_facts.pkg_mgr }}.yml"
- name: OS specifics
  ansible.builtin.include_tasks: "{{ tasks_file }}"
  when: query('file', tasks_file) | length > 0
  vars:
    tasks_file: "os-specifics-{{ ansible_facts.os_family }}.yml"
- name: Install sysstat
  ansible.builtin.include_tasks: sysstat.yml
- name: Users
  ansible.builtin.include_tasks: users.yml
- name: Poor mans DNS
  ansible.builtin.include_tasks: poor_mans_dns.yml
  when: linux_poor_mans_dns
