---

- name: PostgreSQL system config folder
  ansible.builtin.file:
    state: directory
    dest: /etc/postgresql-common
    owner: root
    group: root
    mode: "0755"

- name: Disable autostart of services and cluster creation
  ansible.builtin.copy:
    dest: "{{ item.key }}"
    content: "{{ item.value }}"
    owner: root
    group: root
    mode: "0755"
  loop: '{{ files | dict2items }}'
  vars:
    files:
      "/usr/sbin/policy-rc.d": |
        exit 101
      "/etc/postgresql-common/createcluster.conf": |
        create_main_cluster = false

- name: Download PostgreSQL GPG key
  ansible.builtin.get_url:
    url: "{{ item.value }}"
    dest: "/etc/apt/keyrings/{{ item.key }}.asc"
    mode: '0644'
  loop: "{{ linux_gpg_keys.apt | dict2items }}"

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb {{ item.repo }}"
    state: present
  loop: "{{ linux_public_repos }}"

- name: Upgrade all packages
  ansible.builtin.package:
    name: "*"
    state: "{{ linux_package_state }}"
  when: linux_package_state == 'latest'
  async: 600
  poll: 5

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ linux_package_state }}"
    update_cache: "true"
  loop: "{{ linux_packages | bygroup(group_names) }}"
