---

- name: Add IP Addresses of all hosts to all hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ hostvars[item].ansible_hostname }}$'
    line: >-
      {%- set hv = hostvars[item] -%}
      {{ "%-15s" | format(hv.ansible_host) }} {{ hv.ansible_fqdn }} {{ hv.ansible_hostname }}
    state: present
  loop: '{{ groups.all }}'
  delegate_to: localhost
  when:
    - "item not in groups.localhosts"
